# Generated by Django 4.0.5 on 2022-06-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Input', '0002_alter_field_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
