# Generated by Django 4.0.5 on 2022-07-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Input', '0003_alter_field_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='requestType',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
