# Generated by Django 4.0.5 on 2022-07-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Input', '0004_field_requesttype_alter_field_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='relativebrightness',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='thresholdvalue',
            field=models.IntegerField(null=True),
        ),
    ]
