# Generated by Django 4.0.5 on 2022-07-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Input', '0006_alter_field_thresholdvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='relativebrightness',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='thresholdvalue',
            field=models.IntegerField(null=True),
        ),
    ]
